<a href="https://colab.research.google.com/github/Neelima-git/iris_dataset/blob/master/iris_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing important libraries pandas and numpy: 


In [ ]:
import pandas as pd
import numpy as np


**Exploring the Data:**
Using Iris dataset as the data. It is included in scikit learn in dataset modules. And then we can load it by calling the load_iris function:

In [ ]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

The iris object returned by the load_iris is a Bunch object, which is very similar to dictionary.It conains keys and values. Here, we are printing only the keys that are present in iris_dataset dictionary which is returned by load_iris() function:

In [ ]:
print("Keys of iris_dataset: {} ".format(iris_dataset.keys()))

Keys of iris_dataset: dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename']) 


The value of the key DESCR is a short description of the dataset. This is what it contains:

In [ ]:
val = iris_dataset['DESCR']
start_val = val[:200]
print(start_val+ "\n ..." )

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
 ...


The value of the key target_names is an array of strings, containing the species of flower that we want to predict:

In [ ]:
print("Target names: {}".format(iris_dataset['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


Printing all the features of the flowers species which are our targets

In [ ]:
print("Feature names: \n {}".format(iris_dataset['feature_names']))

Feature names: 
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Looking at the value present in data:

In [ ]:
print("Type of data: {} ".format(type(iris_dataset['data'])))


Type of data: <class 'numpy.ndarray'> 


In [ ]:
print("Shape of data: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


In [ ]:
print("First five rows of data: \n {}".format(iris_dataset['data'][:5]))

First five columns of data: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
print("Type of target: {} ".format(type(iris_dataset['target'])))


Type of target: <class 'numpy.ndarray'> 


In [ ]:
print("Shape of target: {}".format(iris_dataset['target'].shape))


Shape of target: (150,)


In [ ]:
print("Target:\n{}".format(iris_dataset['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


sklearn is an important machine learning framework. We are using the train_test_split function to split the entire iris data in 75 and 25 percent.The capital X denotes the 4 different attributes i.e length  of the petal,width of the petal, length of the sepal, width of the sepal. The small y denotes the labels that is the 3 categories in which the flower can be divided(santosa, versicolor, verginica)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
                                   iris_dataset['data'], iris_dataset['target'], random_state=0)

The output of the train_test_split function is X_train, X_test, y_train, y_test, which are all NumPy arrays. X_train contains 75% of the rows of the dataset, and X_test contains the remaining 25%.

In [ ]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("x_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_train shape: (112, 4)
y_train shape: (112,)
x_test shape: (38, 4)
y_test shape: (38,)


**Created a training model** with **K nearest neighbor** machine learning model

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

Training the above created model. I used knn.fit object with X_train, y_train as arguments passed which will fit the entire k nearest neighbor classifier algorithm to the X_train and y_train

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

**Making predictions** using above model on new data for which we might not know the correct labels

In [ ]:
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape: {}".format(X_new.shape))
X_new.shape: (1, 4)

X_new.shape: (1, 4)


In [ ]:
prediction = knn.predict(X_new)

print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(
    iris_dataset['target_names'][prediction]))

Prediction: [0]
Predicted target name: ['setosa']


**Evaluating the model** that is testing the model on test dataset

In [ ]:
y_pred = knn.predict(X_test)
print("Test set predictions: \n {}".format(y_pred))

Test set predictions: 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


Checking whether the predictions are right or wrong. If the predicted value on test datapoint given by model is equal to the actual value of that datapoint then test set score will give us 1. Othewise if its not equal it will give 0.On getting all these scores we will mean to find the actual accuracy.

In [ ]:
print("Test set score: {}".format(np.mean(y_pred == y_test)))

Test set score: 0.9736842105263158
